(define-constant ERR-NOT-VERIFIED u100)
(define-constant ERR-ALREADY-PAID u101)
(define-constant ERR-INSUFFICIENT-FUNDS u102)
(define-constant ERR-INVALID-BENEFICIARY u103)
(define-constant ERR-INVALID-MILESTONE u104)
(define-constant ERR-INVALID-AMOUNT u105)
(define-constant ERR-POOL-NOT-FUNDED u106)
(define-constant ERR-ORACLE-FAILED u107)
(define-constant ERR-CLAIM-NOT-SUBMITTED u108)
(define-constant ERR-GOVERNANCE-NOT-APPROVED u109)
(define-constant ERR-INVALID-CLAIM-ID u110)
(define-constant ERR-PAYMENT-EXCEEDS-MAX u111)
(define-constant ERR-TIMESTAMP-EXPIRED u112)
(define-constant ERR-BENEFICIARY-NOT-REGISTERED u113)
(define-constant ERR-MILESTONE-NOT-ACHIEVED u114)
(define-data-var pool-balance uint u0)
(define-data-var max-payment-per-claim uint u10000)
(define-data-var governance-token principal 'SP000000000000000000002Q6VF78)
(define-data-var oracle-contract principal 'SP000000000000000000002Q6VF78)
(define-map payments
  { beneficiary: principal, milestone-id: uint }
  { paid: bool, amount: uint, timestamp: uint, claim-id: uint }
)
(define-map claims
  { claim-id: uint }
  { beneficiary: principal, milestone-id: uint, proof-hash: (string-ascii 64), submitted: uint }
)
(define-map milestone-rewards
  uint
  { reward-amount: uint, max-claims: uint, active: bool }
)
(define-private (validate-beneficiary (ben principal))
  (if (is-principal ben) (ok true) (err ERR-INVALID-BENEFICIARY))
)
(define-private (validate-milestone (mid uint))
  (if (> mid u0) (ok true) (err ERR-INVALID-MILESTONE))
)
(define-private (validate-amount (amt uint))
  (if (and (> amt u0) (<= amt (var-get max-payment-per-claim))) (ok true) (err ERR-INVALID-AMOUNT))
)
(define-private (validate-claim-id (cid uint))
  (if (> cid u0) (ok true) (err ERR-INVALID-CLAIM-ID))
)
(define-private (check-funds (amt uint))
  (if (>= (var-get pool-balance) amt) (ok true) (err ERR-INSUFFICIENT-FUNDS))
)
(define-private (is-claim-submitted (cid uint))
  (is-some (map-get? claims { claim-id: cid }))
)
(define-private (is-milestone-verified (cid uint))
  (let ((oracle (var-get oracle-contract)))
    (contract-call? oracle verify-claim cid)
  )
)
(define-private (is-payment-made (ben principal) (mid uint))
  (is-some (map-get? payments { beneficiary: ben, milestone-id: mid }))
)
(define-private (get-milestone-reward (mid uint))
  (map-get? milestone-rewards mid)
)
(define-read-only (get-payment-status (ben principal) (mid uint))
  (map-get? payments { beneficiary: ben, milestone-id: mid })
)
(define-read-only (get-claim-details (cid uint))
  (map-get? claims { claim-id: cid })
)
(define-read-only (get-pool-balance)
  (var-get pool-balance)
)
(define-read-only (get-max-payment)
  (var-get max-payment-per-claim)
)
(define-public (set-oracle-contract (ora principal))
  (begin
    (asserts! (is-eq tx-sender (var-get governance-token)) (err ERR-GOVERNANCE-NOT-APPROVED))
    (var-set oracle-contract ora)
    (ok true)
  )
)
(define-public (set-max-payment-per-claim (max uint))
  (begin
    (asserts! (is-eq tx-sender (var-get governance-token)) (err ERR-GOVERNANCE-NOT-APPROVED))
    (asserts! (> max u0) (err ERR-INVALID-AMOUNT))
    (var-set max-payment-per-claim max)
    (ok true)
  )
)
(define-public (fund-pool (amt uint))
  (let ((sender tx-sender))
    (asserts! (> amt u0) (err ERR-INVALID-AMOUNT))
    (try! (stx-transfer? amt sender (as-contract tx-sender)))
    (var-set pool-balance (+ (var-get pool-balance) amt))
    (ok true)
  )
)
(define-public (submit-claim (cid uint) (mid uint) (proof (string-ascii 64)))
  (begin
    (try! (validate-claim-id cid))
    (try! (validate-milestone mid))
    (asserts! (not (is-some (map-get? claims { claim-id: cid }))) (err ERR-CLAIM-NOT-SUBMITTED))
    (map-set claims { claim-id: cid }
      { beneficiary: tx-sender, milestone-id: mid, proof-hash: proof, submitted: block-height }
    )
    (print { event: "claim-submitted", claim-id: cid, milestone: mid })
    (ok cid)
  )
)
(define-public (dispatch-payment (cid uint))
  (let* (
         (claim (unwrap! (map-get? claims { claim-id: cid }) (err ERR-INVALID-CLAIM-ID)))
         (ben (get beneficiary claim))
         (mid (get milestone-id claim))
         (proof (get proof-hash claim))
         (reward-opt (get-milestone-reward mid))
         (reward (unwrap! reward-opt (err ERR-INVALID-MILESTONE)))
         (amt (get reward-amount reward))
         (timestamp (get submitted claim))
       )
    (try! (validate-beneficiary ben))
    (try! (validate-amount amt))
    (try! (check-funds amt))
    (asserts! (not (is-payment-made ben mid)) (err ERR-ALREADY-PAID))
    (asserts! (>= block-height (+ timestamp u86400)) (err ERR-TIMESTAMP-EXPIRED)) ;; 1 day wait
    (try! (is-milestone-verified cid))
    (asserts! (get active reward) (err ERR-MILESTONE-NOT-ACHIEVED))
    (as-contract (stx-transfer? amt (as-contract tx-sender) ben))
    (var-set pool-balance (- (var-get pool-balance) amt))
    (map-set payments { beneficiary: ben, milestone-id: mid }
      { paid: true, amount: amt, timestamp: block-height, claim-id: cid }
    )
    (print { event: "payment-dispatched", beneficiary: ben, amount: amt, milestone: mid })
    (ok amt)
  )
)
(define-public (set-milestone-reward (mid uint) (amt uint) (maxc uint))
  (begin
    (asserts! (is-eq tx-sender (var-get governance-token)) (err ERR-GOVERNANCE-NOT-APPROVED))
    (try! (validate-milestone mid))
    (try! (validate-amount amt))
    (map-set milestone-rewards mid
      { reward-amount: amt, max-claims: maxc, active: true }
    )
    (ok true)
  )
)
(define-public (deactivate-milestone (mid uint))
  (begin
    (asserts! (is-eq tx-sender (var-get governance-token)) (err ERR-GOVERNANCE-NOT-APPROVED))
    (try! (validate-milestone mid))
    (map-set milestone-rewards mid
      { reward-amount: (get reward-amount (unwrap! (get-milestone-reward mid) (err ERR-INVALID-MILESTONE))),
        max-claims: (get max-claims (unwrap! (get-milestone-reward mid) (err ERR-INVALID-MILESTONE))),
        active: false }
    )
    (ok true)
  )
)
(define-public (withdraw-excess (amt uint))
  (let ((gov (var-get governance-token)))
    (asserts! (is-eq tx-sender gov) (err ERR-GOVERNANCE-NOT-APPROVED))
    (try! (validate-amount amt))
    (try! (check-funds amt))
    (as-contract (stx-transfer? amt (as-contract tx-sender) gov))
    (var-set pool-balance (- (var-get pool-balance) amt))
    (ok true)
  )
)